features:
  name: 0
  slogan: 1
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://rosemont-logo-horizontal-2.png'
favicon:
  use_default: 0
  path: 'public://rosemont-logo-square.png'
  mimetype: image/png
