features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://rosemont-logo-horizontal-2.png'
favicon:
  use_default: 1
show_breadcrumbs: 1
slideshow_display: 0
slide1_head: 'Sample product'
slide1_desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt elit, sed do eiusmod tempor...'
slide1_url: node/1
slide1_image: {  }
slide2_head: 'Sample service'
slide2_desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do Lorem ipsum dolor sit amet irure dolor in reprehenderit...'
slide2_url: node/2
slide2_image: {  }
slide3_head: 'Contact us'
slide3_desc: 'Duis aute irure dolor in reprehenderit inLorem ipsum dolor sit amet, consectetur do Lorem ipsum dolor sit amet irure...'
slide3_url: node/3
slide3_image: {  }
