features:
  name: 0
  slogan: 0
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://scholars-trust-web.png'
favicon:
  use_default: 0
  path: 'public://scholars-trust-round.png'
  mimetype: image/png
